# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tierlist CI Pipeline

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build, Test, Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install deps
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Create index.html Fallback
      # this next step makes all routes go to index.html for GitHub Pages
      # for more, see https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml
      run: cp dist/tierlist/index.html dist/tierlist/404.html
    - name: Validate
      run: npm test

    # - name: Archive build
      # if: success()
      # uses: actions/upload-artifact@v2
      # with:
        # name: deploy_dist
        # path: dist
    - name: Deploy to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/tierlist
        CLEAN: true
